### ISSUE TITLE
메인 페이지 타이틀 변경

### ISSUE THREAD

**Issue by dahli4** [whgurrb/mastering-git-github#3]
- 기존 페이지 메인 타이틀 변경이 필요합니다.
- 변경내용 : 운영팀 웹 어드민 시스템

**Comment by whgurrb** [comment]
새로운 기능 구현이 시간이 얼마나 배정할 겁니까?

**Comment by dahli4** [comment]
> 새로운 기능 구현이 시간이 얼마나 배정할 겁니까?

10분입니다.
